export const worldCupCountrySeeds = {
  ALG: {
    fifaCode: "ALG",
    name: "Algeria",
    flagEmoji: "🇩🇿",
    capital: "Algiers",
    region: "Africa",
    subregion: "Northern Africa",
    coordinates: [28, 3],
    languages: ["Arabic"],
    currency: "Algerian dinar",
  },
  ARG: {
    fifaCode: "ARG",
    name: "Argentina",
    flagEmoji: "🇦🇷",
    capital: "Buenos Aires",
    region: "South America",
    subregion: "Southern Cone",
    coordinates: [-34, -64],
    languages: ["Guarani", "Spanish"],
    currency: "Argentine peso",
  },
  AUS: {
    fifaCode: "AUS",
    name: "Australia",
    flagEmoji: "🇦🇺",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    coordinates: [-27, 133],
    languages: ["English"],
    currency: "Australian dollar",
  },
  AUT: {
    fifaCode: "AUT",
    name: "Austria",
    flagEmoji: "🇦🇹",
    capital: "Vienna",
    region: "Europe",
    subregion: "Central Europe",
    coordinates: [47.33333333, 13.33333333],
    languages: ["Austro-Bavarian German"],
    currency: "Euro",
  },
  BEL: {
    fifaCode: "BEL",
    name: "Belgium",
    flagEmoji: "🇧🇪",
    capital: "Brussels",
    region: "Europe",
    subregion: "Western Europe",
    coordinates: [50.83333333, 4],
    languages: ["German", "French", "Dutch"],
    currency: "Euro",
  },
  BIH: {
    fifaCode: "BIH",
    name: "Bosnia-Herzegovina",
    flagEmoji: "🇧🇦",
    capital: "Sarajevo",
    region: "Europe",
    subregion: "Southeast Europe",
    coordinates: [44, 18],
    languages: ["Bosnian", "Croatian", "Serbian"],
    currency: "Bosnia and Herzegovina convertible mark",
  },
  BRA: {
    fifaCode: "BRA",
    name: "Brazil",
    flagEmoji: "🇧🇷",
    capital: "Brasilia",
    region: "South America",
    subregion: "South America",
    coordinates: [-10, -55],
    languages: ["Portuguese"],
    currency: "Brazilian real",
  },
  CAN: {
    fifaCode: "CAN",
    name: "Canada",
    flagEmoji: "🇨🇦",
    capital: "Ottawa",
    region: "North America",
    subregion: "North America",
    coordinates: [60, -95],
    languages: ["English", "French"],
    currency: "Canadian dollar",
  },
  CPV: {
    fifaCode: "CPV",
    name: "Cape Verde",
    flagEmoji: "🇨🇻",
    capital: "Praia",
    region: "Africa",
    subregion: "Western Africa",
    coordinates: [16, -24],
    languages: ["Portuguese"],
    currency: "Cape Verdean escudo",
  },
  COL: {
    fifaCode: "COL",
    name: "Colombia",
    flagEmoji: "🇨🇴",
    capital: "Bogota",
    region: "South America",
    subregion: "South America",
    coordinates: [4, -72],
    languages: ["Spanish"],
    currency: "Colombian peso",
  },
  COD: {
    fifaCode: "COD",
    name: "Congo DR",
    flagEmoji: "🇨🇩",
    capital: "Kinshasa",
    region: "Africa",
    subregion: "Middle Africa",
    coordinates: [0, 25],
    languages: ["French", "Kikongo", "Lingala", "Tshiluba", "Swahili"],
    currency: "Congolese franc",
  },
  CRO: {
    fifaCode: "CRO",
    name: "Croatia",
    flagEmoji: "🇭🇷",
    capital: "Zagreb",
    region: "Europe",
    subregion: "Southeast Europe",
    coordinates: [45.16666666, 15.5],
    languages: ["Croatian"],
    currency: "Euro",
  },
  CUW: {
    fifaCode: "CUW",
    name: "Curacao",
    flagEmoji: "🇨🇼",
    capital: "Willemstad",
    region: "North America",
    subregion: "Caribbean",
    coordinates: [12.116667, -68.933333],
    languages: ["English", "Dutch", "Papiamento"],
    currency: "Netherlands Antillean guilder",
  },
  CZE: {
    fifaCode: "CZE",
    name: "Czechia",
    flagEmoji: "🇨🇿",
    capital: "Prague",
    region: "Europe",
    subregion: "Central Europe",
    coordinates: [49.75, 15.5],
    languages: ["Czech", "Slovak"],
    currency: "Czech koruna",
  },
  ECU: {
    fifaCode: "ECU",
    name: "Ecuador",
    flagEmoji: "🇪🇨",
    capital: "Quito",
    region: "South America",
    subregion: "South America",
    coordinates: [-2, -77.5],
    languages: ["Spanish"],
    currency: "United States dollar",
  },
  EGY: {
    fifaCode: "EGY",
    name: "Egypt",
    flagEmoji: "🇪🇬",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    coordinates: [27, 30],
    languages: ["Arabic"],
    currency: "Egyptian pound",
  },
  ENG: {
    fifaCode: "ENG",
    name: "England",
    flagEmoji: "🏴",
    flagImageUrl: "/flags/england.svg",
    capital: "London",
    region: "Europe",
    subregion: "British Isles",
    coordinates: [51.5072, -0.1276],
    languages: ["English"],
    currency: "Pound sterling",
    population: 57000000,
  },
  FRA: {
    fifaCode: "FRA",
    name: "France",
    flagEmoji: "🇫🇷",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
    coordinates: [46, 2],
    languages: ["French"],
    currency: "Euro",
  },
  GER: {
    fifaCode: "GER",
    name: "Germany",
    flagEmoji: "🇩🇪",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
    coordinates: [51, 9],
    languages: ["German"],
    currency: "Euro",
  },
  GHA: {
    fifaCode: "GHA",
    name: "Ghana",
    flagEmoji: "🇬🇭",
    capital: "Accra",
    region: "Africa",
    subregion: "Western Africa",
    coordinates: [8, -2],
    languages: ["English"],
    currency: "Ghanaian cedi",
  },
  HAI: {
    fifaCode: "HAI",
    name: "Haiti",
    flagEmoji: "🇭🇹",
    capital: "Port-au-Prince",
    region: "North America",
    subregion: "Caribbean",
    coordinates: [19, -72.41666666],
    languages: ["French", "Haitian Creole"],
    currency: "Haitian gourde",
  },
  IRN: {
    fifaCode: "IRN",
    name: "Iran",
    flagEmoji: "🇮🇷",
    capital: "Tehran",
    region: "Asia",
    subregion: "Southern Asia",
    coordinates: [32, 53],
    languages: ["Persian (Farsi)"],
    currency: "Iranian rial",
  },
  IRQ: {
    fifaCode: "IRQ",
    name: "Iraq",
    flagEmoji: "🇮🇶",
    capital: "Baghdad",
    region: "Asia",
    subregion: "Western Asia",
    coordinates: [33, 44],
    languages: ["Arabic", "Aramaic", "Sorani"],
    currency: "Iraqi dinar",
  },
  CIV: {
    fifaCode: "CIV",
    name: "Ivory Coast",
    flagEmoji: "🇨🇮",
    capital: "Yamoussoukro",
    region: "Africa",
    subregion: "Western Africa",
    coordinates: [8, -5],
    languages: ["French"],
    currency: "West African CFA franc",
  },
  JPN: {
    fifaCode: "JPN",
    name: "Japan",
    flagEmoji: "🇯🇵",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    coordinates: [36, 138],
    languages: ["Japanese"],
    currency: "Japanese yen",
  },
  JOR: {
    fifaCode: "JOR",
    name: "Jordan",
    flagEmoji: "🇯🇴",
    capital: "Amman",
    region: "Asia",
    subregion: "Western Asia",
    coordinates: [31, 36],
    languages: ["Arabic"],
    currency: "Jordanian dinar",
  },
  MEX: {
    fifaCode: "MEX",
    name: "Mexico",
    flagEmoji: "🇲🇽",
    capital: "Mexico City",
    region: "North America",
    subregion: "North America",
    coordinates: [23, -102],
    languages: ["Spanish"],
    currency: "Mexican peso",
  },
  MAR: {
    fifaCode: "MAR",
    name: "Morocco",
    flagEmoji: "🇲🇦",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
    coordinates: [32, -5],
    languages: ["Arabic", "Berber"],
    currency: "Moroccan dirham",
  },
  NED: {
    fifaCode: "NED",
    name: "Netherlands",
    flagEmoji: "🇳🇱",
    capital: "Amsterdam",
    region: "Europe",
    subregion: "Western Europe",
    coordinates: [52.5, 5.75],
    languages: ["Dutch"],
    currency: "Euro",
  },
  NZL: {
    fifaCode: "NZL",
    name: "New Zealand",
    flagEmoji: "🇳🇿",
    capital: "Wellington",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    coordinates: [-41, 174],
    languages: ["English", "Maori", "New Zealand Sign Language"],
    currency: "New Zealand dollar",
  },
  NOR: {
    fifaCode: "NOR",
    name: "Norway",
    flagEmoji: "🇳🇴",
    capital: "Oslo",
    region: "Europe",
    subregion: "Northern Europe",
    coordinates: [62, 10],
    languages: ["Norwegian Nynorsk", "Norwegian Bokmal", "Sami"],
    currency: "Norwegian krone",
  },
  PAN: {
    fifaCode: "PAN",
    name: "Panama",
    flagEmoji: "🇵🇦",
    capital: "Panama City",
    region: "North America",
    subregion: "Central America",
    coordinates: [9, -80],
    languages: ["Spanish"],
    currency: "Panamanian balboa",
  },
  PAR: {
    fifaCode: "PAR",
    name: "Paraguay",
    flagEmoji: "🇵🇾",
    capital: "Asuncion",
    region: "South America",
    subregion: "South America",
    coordinates: [-23, -58],
    languages: ["Guarani", "Spanish"],
    currency: "Paraguayan guarani",
  },
  POR: {
    fifaCode: "POR",
    name: "Portugal",
    flagEmoji: "🇵🇹",
    capital: "Lisbon",
    region: "Europe",
    subregion: "Southern Europe",
    coordinates: [39.5, -8],
    languages: ["Portuguese"],
    currency: "Euro",
  },
  QAT: {
    fifaCode: "QAT",
    name: "Qatar",
    flagEmoji: "🇶🇦",
    capital: "Doha",
    region: "Asia",
    subregion: "Western Asia",
    coordinates: [25.5, 51.25],
    languages: ["Arabic"],
    currency: "Qatari riyal",
  },
  KSA: {
    fifaCode: "KSA",
    name: "Saudi Arabia",
    flagEmoji: "🇸🇦",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
    coordinates: [25, 45],
    languages: ["Arabic"],
    currency: "Saudi riyal",
  },
  SCO: {
    fifaCode: "SCO",
    name: "Scotland",
    flagEmoji: "🏴",
    capital: "Edinburgh",
    region: "Europe",
    subregion: "British Isles",
    coordinates: [55.9533, -3.1883],
    languages: ["English", "Scots", "Scottish Gaelic"],
    currency: "Pound sterling",
    population: 5550000,
  },
  SEN: {
    fifaCode: "SEN",
    name: "Senegal",
    flagEmoji: "🇸🇳",
    capital: "Dakar",
    region: "Africa",
    subregion: "Western Africa",
    coordinates: [14, -14],
    languages: ["French"],
    currency: "West African CFA franc",
  },
  RSA: {
    fifaCode: "RSA",
    name: "South Africa",
    flagEmoji: "🇿🇦",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    coordinates: [-29, 24],
    languages: [
      "Afrikaans",
      "English",
      "Southern Ndebele",
      "Northern Sotho",
      "Southern Sotho",
      "Swazi",
      "Tswana",
      "Tsonga",
      "Venda",
      "Xhosa",
      "Zulu",
    ],
    currency: "South African rand",
  },
  KOR: {
    fifaCode: "KOR",
    name: "South Korea",
    flagEmoji: "🇰🇷",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    coordinates: [37, 127.5],
    languages: ["Korean"],
    currency: "South Korean won",
  },
  ESP: {
    fifaCode: "ESP",
    name: "Spain",
    flagEmoji: "🇪🇸",
    capital: "Madrid",
    region: "Europe",
    subregion: "Southern Europe",
    coordinates: [40, -4],
    languages: ["Spanish"],
    currency: "Euro",
  },
  SWE: {
    fifaCode: "SWE",
    name: "Sweden",
    flagEmoji: "🇸🇪",
    capital: "Stockholm",
    region: "Europe",
    subregion: "Northern Europe",
    coordinates: [62, 15],
    languages: ["Swedish"],
    currency: "Swedish krona",
  },
  SUI: {
    fifaCode: "SUI",
    name: "Switzerland",
    flagEmoji: "🇨🇭",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
    coordinates: [47, 8],
    languages: ["French", "Swiss German", "Italian", "Romansh"],
    currency: "Swiss franc",
  },
  TUN: {
    fifaCode: "TUN",
    name: "Tunisia",
    flagEmoji: "🇹🇳",
    capital: "Tunis",
    region: "Africa",
    subregion: "Northern Africa",
    coordinates: [34, 9],
    languages: ["Arabic"],
    currency: "Tunisian dinar",
  },
  TUR: {
    fifaCode: "TUR",
    name: "Turkiye",
    flagEmoji: "🇹🇷",
    capital: "Ankara",
    region: "Asia",
    subregion: "Western Asia",
    coordinates: [39, 35],
    languages: ["Turkish"],
    currency: "Turkish lira",
  },
  USA: {
    fifaCode: "USA",
    name: "United States",
    flagEmoji: "🇺🇸",
    capital: "Washington, D.C.",
    region: "North America",
    subregion: "North America",
    coordinates: [38, -97],
    languages: ["English"],
    currency: "United States dollar",
  },
  URU: {
    fifaCode: "URU",
    name: "Uruguay",
    flagEmoji: "🇺🇾",
    capital: "Montevideo",
    region: "South America",
    subregion: "South America",
    coordinates: [-33, -56],
    languages: ["Spanish"],
    currency: "Uruguayan peso",
  },
  UZB: {
    fifaCode: "UZB",
    name: "Uzbekistan",
    flagEmoji: "🇺🇿",
    capital: "Tashkent",
    region: "Asia",
    subregion: "Central Asia",
    coordinates: [41, 64],
    languages: ["Russian", "Uzbek"],
    currency: "Uzbekistani so'm",
  },
} as const;
